In [3]:
import numpy as np

In [4]:
clean_ds = np.loadtxt("wifi_db/clean_dataset.txt")
noisy_ds = np.loadtxt("wifi_db/noisy_dataset.txt")

In [6]:
print(noisy_ds)
print(clean_ds)

[[-59. -53. -51. ... -79. -87.   4.]
 [-66. -53. -59. ... -81. -79.   1.]
 [-41. -57. -63. ... -66. -65.   2.]
 ...
 [-57. -54. -56. ... -79. -82.   1.]
 [-56. -52. -50. ... -85. -88.   3.]
 [-46. -54. -47. ... -80. -73.   3.]]
[[-64. -56. -61. ... -82. -81.   1.]
 [-68. -57. -61. ... -85. -85.   1.]
 [-63. -60. -60. ... -85. -84.   1.]
 ...
 [-62. -59. -46. ... -87. -88.   4.]
 [-62. -58. -52. ... -90. -85.   4.]
 [-59. -50. -45. ... -88. -87.   4.]]


In [ ]:
def decision_tree_learning(ds, depth):
    if()